# 配置文件路径: configs/dfine/dfine_l_university_6cls.yml

# ==========================================================
# 引用 L 模型基础配置
# ==========================================================
__include__:
  - include/dfine_hgnetv2.yml
  - include/dataloader.yml
  - include/optimizer.yml
  - dfine_hgnetv2_l_coco.yml

# ==========================================================
# 核心参数覆盖
# ==========================================================
epochs: 80                  # L 模型建议 80 轮
num_classes: 6               # 匹配您的 6 个行为类别
remap_mscoco_category: False

# ==========================================================
# 显存与数据加载 (适配 4090 24G 显存)
# ==========================================================
train_dataloader:
  total_batch_size: 8
  num_workers: 4
  dataset:
    img_folder: dataset/0.671k_university_yolo_Dataset/images/train
    ann_file: dataset/0.671k_university_yolo_Dataset/annotations/instances_train.json

  collate_fn:
    stop_epoch: 72           # 最后 8 轮关闭强增强

val_dataloader:
  total_batch_size: 8
  dataset:
    img_folder: dataset/0.671k_university_yolo_Dataset/images/val
    ann_file: dataset/0.671k_university_yolo_Dataset/annotations/instances_val.json
