


__include__:
  - dfine_l_university_6cls.yml

output_dir: ./output/dfine_l_university_6cls_o2m

DFINECriterion:

  use_o2m_aux: True
  o2m_topk: 3

  o2m_loss_weight: 0.25

  o2m_losses: ['vfl', 'boxes']
