


__include__:
  - dfine_l_university_6cls.yml

output_dir: ./output/dfine_l_university_6cls_paq_qao2m


DFINETransformer:

  use_paq_query: False
  use_bcqs: False


DFINECriterion:

  use_o2m_aux: True

  o2m_topk: 3

  o2m_matcher_type: quality
  o2m_quality_gamma: 0.25

  o2m_min_pos: 1

  o2m_loss_weight: 1.0

  o2m_losses: ['vfl', 'boxes']
