



__include__:
  - dfine_l_university_6cls.yml

output_dir: ./output/dfine_l_university_6cls_sbdh


DFINETransformer:

  use_sbdh: True


  sbdh_group_ids: [0, 0, 1, 1, 2, 2]

  sbdh_group_weight: 0.25


  use_paq_query: False
  use_bcqs: False
