



__include__:
  - dfine_l_university_6cls.yml


DFINETransformer:

  use_bcqs: True
  bcqs_kernel_size: 3
  bcqs_score_weight: 0.25


  use_bqfe: True
  bqfe_kernel_size: 3
  bqfe_reduction: 4

  bqfe_init: 0.03
