


__include__:
  - dfine_l_university_6cls.yml

output_dir: ./output/dfine_l_university_6cls_paq_bcqs_m150_gate003

DFINETransformer:

  use_paq_query: False
  use_bcqs: False



  use_paq_bcqs_fusion: True
  paq_bcqs_num_patterns: 150
  paq_bcqs_kernel_size: 3


  bcqs_learn_score_weight: False
  paq_bcqs_score_weight: 0.25


  paq_bcqs_gate_init: 0.03
