



__include__:
  - dfine_l_university_6cls.yml

output_dir: ./output/dfine_l_university_6cls_simam


HybridEncoder:

  use_simam: True

  simam_e_lambda: 0.0001


  use_bmefs: False

DFINETransformer:

  use_bcqs: False
  use_paq_query: False
